import logging
import os
import random
import redis

logging.basicConfig(datefmt='%Y/%m/%d %X', format='%(asctime)s: %(message)s', level=os.environ.get('LOG_LEVEL', 'INFO'))
logger = logging.getLogger(__name__)

# https://www.lipsum.com/
messages = '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget ultrices lorem. Aliquam erat volutpat. Maecenas condimentum congue diam, vel aliquam libero porta quis. Morbi porta diam id ultrices vestibulum. Aliquam rhoncus, ante ut rhoncus faucibus, tellus nisi volutpat nibh, a aliquet orci nibh sit amet orci. Duis laoreet ultricies metus convallis blandit. Vestibulum dignissim molestie lacus, id cursus enim scelerisque quis. Fusce ut odio maximus, hendrerit lorem in, laoreet tortor. Vivamus eget cursus nisl, a facilisis ante. Mauris bibendum, urna ac tristique commodo, metus diam commodo dolor, vel commodo dolor mi sit amet dolor. Phasellus finibus ipsum massa, et aliquam odio auctor convallis. Quisque ultricies tellus nunc. Vestibulum eu interdum turpis. Pellentesque facilisis rutrum imperdiet. Aenean dapibus in sapien a maximus. Duis sed magna lacinia, hendrerit dui luctus, facilisis nunc.

Nunc eu aliquet enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam nisi sapien, dignissim ac blandit convallis, tempus vel felis. Etiam sit amet ornare nunc, a tincidunt urna. Nam eu gravida dui. Maecenas auctor fringilla nunc nec volutpat. Sed pulvinar urna tellus, id aliquet velit vulputate vel.

Aliquam sed lorem convallis augue sagittis varius. Morbi id convallis enim. Mauris urna diam, consectetur id justo quis, volutpat volutpat eros. Vivamus ut metus lorem. Vivamus tincidunt mi massa, at rutrum lacus tincidunt sed. Donec rutrum luctus urna ut iaculis. Ut vitae sem ac tellus fringilla consectetur. Etiam a felis pretium, iaculis lacus vel, congue lacus. Nunc dictum eros diam, condimentum condimentum sapien congue a. Donec ac mauris sit amet lacus scelerisque sodales id eget leo. Pellentesque vel odio quis magna efficitur vestibulum a non risus. Curabitur blandit nunc quis metus varius semper. Etiam fermentum elit in tortor sollicitudin consectetur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed aliquam eu tellus sit amet porttitor. Fusce feugiat, risus id vehicula semper, nunc felis lacinia tellus, eu dignissim erat est in lectus.

Curabitur id elit sed odio malesuada rutrum. Quisque eros felis, vestibulum ut nibh id, porttitor sodales mauris. Maecenas molestie egestas justo, vel volutpat ex. Vestibulum dapibus hendrerit turpis nec pretium. Nunc efficitur nisi sit amet orci posuere malesuada. Nullam porttitor facilisis quam, a ornare tellus porttitor dictum. Ut fringilla orci et ligula sodales lobortis eget commodo nulla.

Suspendisse tristique, diam a dapibus fringilla, diam sapien euismod augue, vehicula imperdiet odio dolor at sem. Sed eu lobortis felis, non vulputate ligula. Integer non interdum sapien. Suspendisse vel diam dignissim nisl consectetur ultrices quis a dolor. Donec et ultricies nisi. Aliquam erat volutpat. Nullam et mauris vitae ligula scelerisque luctus vel fermentum arcu. Nullam dapibus elit vel est malesuada, et placerat erat cursus. Ut vehicula non diam eu molestie. Duis dictum orci ac luctus congue.

Suspendisse varius tincidunt elit, eget luctus risus lacinia at. Fusce sapien felis, dapibus eget augue et, aliquet gravida justo. Vivamus molestie eu velit eget auctor. Mauris in neque eget magna cursus finibus a ut tellus. Nunc gravida bibendum convallis. Cras eu elementum lacus, eu tristique arcu. Quisque leo ligula, lacinia eget diam non, consectetur egestas velit. Curabitur congue vulputate enim eget euismod. In quis feugiat ex. Integer non malesuada ante. Cras fringilla elementum eros, quis lacinia ex tempor vel. Vestibulum pharetra quam metus, at finibus est lobortis a. Aliquam fringilla tristique risus a bibendum.

Fusce non ante risus. Mauris et accumsan urna. Fusce massa tellus, faucibus eget urna vitae, tempor facilisis tellus. Donec et eros ornare, ullamcorper sapien sed, pharetra ligula. Nam in malesuada lectus. Pellentesque vel nunc et leo gravida pulvinar. Cras lobortis neque ex, ut lacinia dolor tincidunt id. Quisque varius condimentum nibh. Quisque elementum bibendum tempus. Vivamus leo erat, imperdiet nec iaculis quis, efficitur sit amet arcu. In ultricies pellentesque lobortis. Donec sit amet sodales lorem. Morbi vestibulum arcu sed lacus venenatis, sit amet blandit odio sagittis. Fusce porttitor magna velit, eu rutrum dolor rhoncus id.

Sed sed felis ut dui laoreet pharetra et vel turpis. Nullam quis augue quam. Morbi elit sapien, venenatis efficitur dapibus sit amet, laoreet vel neque. Phasellus in dapibus risus, id porta massa. Suspendisse potenti. Praesent ullamcorper sed urna eu ultrices. Nulla lacinia ullamcorper hendrerit. Curabitur vehicula nisl in augue tristique porta. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque leo erat, finibus eu velit in, pulvinar condimentum ipsum. Vestibulum molestie, felis quis cursus rutrum, magna dolor lobortis neque, quis lacinia justo felis eu odio.

Fusce sit amet augue velit. Mauris tincidunt dictum quam, et vulputate nibh commodo ac. Donec sit amet commodo ante, ac maximus risus. Proin ultrices massa euismod, faucibus lorem in, placerat magna. Vivamus faucibus, velit eget imperdiet sagittis, turpis dui luctus felis, vitae congue turpis diam in purus. Maecenas fermentum purus urna, vitae malesuada diam fermentum sed. Vestibulum sagittis augue non quam suscipit, at consequat erat mollis. Pellentesque id imperdiet nibh. Cras sit amet consectetur ipsum, at aliquam sapien. Suspendisse tincidunt, ipsum suscipit malesuada rutrum, ligula turpis suscipit massa, at tempus tellus ex vehicula leo. Mauris non ligula id eros cursus lobortis in sed ligula. Suspendisse in nunc est. Morbi ac turpis in urna malesuada interdum ut eget tortor. Sed in ipsum mauris. Etiam eu blandit leo.

Sed tempor felis enim, nec euismod metus tristique vel. In hac habitasse platea dictumst. Sed volutpat massa vitae tellus suscipit, quis ullamcorper elit pretium. Donec feugiat, justo id aliquam suscipit, magna augue tempor sapien, id pharetra diam metus ac ipsum. Aenean sed ultrices mauris. Sed condimentum euismod magna, placerat ornare dolor congue id. Cras sapien risus, faucibus molestie urna gravida, ullamcorper consequat quam. Proin sed nisl quam. Nullam gravida diam justo, vel vulputate arcu bibendum in. Phasellus consequat quam sit amet interdum congue. Morbi massa sapien, sagittis a turpis ut, luctus gravida dui. Morbi sapien dolor, faucibus ac auctor eget, bibendum vel orci. Cras nec lobortis neque. Nunc id dui sollicitudin, malesuada turpis eget, condimentum tellus. Suspendisse vehicula laoreet mi quis pellentesque.

Cras eu diam mauris. Nunc quis diam sit amet quam posuere finibus vel a ex. Suspendisse sit amet purus fringilla, bibendum dolor a, mattis risus. Quisque convallis nibh pulvinar, dapibus enim id, lacinia augue. Nunc erat lacus, mattis molestie tellus ac, porttitor aliquet tellus. Aenean ut nisi elit. Ut elementum tristique lacus. Donec luctus, neque id tempus iaculis, libero dui tempor magna, vitae aliquam tellus lorem eget ante. Nunc accumsan urna ligula.

Etiam ac nunc consectetur, consequat sem at, tempus massa. Sed sit amet nunc porttitor erat ultricies vehicula. Quisque gravida ut nisi vitae commodo. Phasellus lobortis nec est sed mattis. Mauris lectus turpis, aliquam non maximus quis, sollicitudin id enim. Curabitur sem purus, pellentesque vitae magna vel, gravida lobortis magna. Quisque tellus enim, vehicula imperdiet purus et, porta ultricies ex. Suspendisse ut arcu et quam aliquam dictum. Fusce nisl lacus, cursus a odio in, suscipit sagittis risus. Aenean laoreet nec sapien scelerisque ullamcorper. Sed libero nisi, volutpat quis nisl nec, volutpat ultrices velit. Fusce elementum augue eros, ut viverra mi lobortis vel.

Duis in sapien risus. Suspendisse potenti. In eu fringilla massa. Vestibulum ornare lectus purus, et ullamcorper nisl egestas a. Nam cursus varius risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut egestas urna ut quam posuere, ac sodales ex scelerisque. Quisque bibendum nunc ligula, eget tristique justo imperdiet a.

Nulla et magna augue. Ut consectetur eu dolor tempor convallis. Duis fringilla hendrerit est, eleifend ultricies mauris finibus a. In hac habitasse platea dictumst. Vivamus vitae pulvinar mi, in suscipit dui. Suspendisse eu volutpat purus. Nam ante nunc, suscipit ut dignissim sit amet, pellentesque in tellus. Vivamus condimentum nulla nibh, in sagittis massa lacinia vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec aliquet urna feugiat urna ultricies, id efficitur dolor euismod. Suspendisse interdum velit id pellentesque suscipit.

Praesent convallis ultricies nulla ac varius. Nunc mattis fermentum risus eget varius. Sed congue quam quis ipsum egestas, vitae pretium ex auctor. Donec ut nunc sed magna molestie eleifend. Phasellus sit amet semper sapien. In commodo nec elit vitae sollicitudin. Vivamus ac tempor mauris. Ut magna augue, pulvinar aliquet velit et, tristique feugiat nulla. Etiam et iaculis sem. Nam bibendum rhoncus egestas. Fusce nunc ipsum, luctus quis lectus dictum, porta fringilla ex. Curabitur euismod scelerisque nulla at sodales. Praesent a blandit mi. Nunc mollis egestas enim mattis sodales. Proin pellentesque quam vitae dolor sollicitudin fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Pellentesque id suscipit purus. Nulla facilisi. Nunc pellentesque feugiat dui. Mauris nec magna ac risus cursus porta ac vel mauris. Fusce ullamcorper sodales arcu sodales dignissim. Ut blandit dui eget ultrices aliquam. Aliquam congue sapien risus, vitae tincidunt massa accumsan et. Ut at arcu mattis, porta purus non, auctor erat. Duis consectetur, ante non feugiat aliquam, dui purus auctor enim, sed interdum felis erat a tellus. Curabitur tellus ligula, aliquam sed suscipit in, fringilla eget lacus. Pellentesque nec velit eget quam facilisis consectetur. Nunc purus nisl, aliquam quis bibendum a, porta tristique quam. Curabitur porttitor hendrerit mi a tincidunt. Phasellus sit amet purus ipsum.

Quisque et cursus metus. Phasellus a lacinia tortor. Cras nec neque felis. Vivamus at tincidunt magna. Morbi ut ex nec quam tristique eleifend. Vestibulum vitae rhoncus orci. Suspendisse volutpat tincidunt ligula at pellentesque. Cras purus nunc, aliquam vitae ex vitae, semper dapibus nibh. Suspendisse potenti. Suspendisse consequat massa nec dui porta molestie. Pellentesque scelerisque, purus id lacinia tincidunt, ipsum libero placerat tellus, eget tristique quam enim a arcu. Sed ac libero sapien. Donec et ligula non libero elementum vulputate in a elit. Integer porttitor est ut metus tristique, sodales dapibus ex lacinia. Aliquam vel metus non orci tristique fringilla vel quis nisl. Donec congue, mi ut pretium iaculis, ligula felis vestibulum dui, malesuada imperdiet mauris sem vitae ante.

In vulputate lobortis elit, sed iaculis sem accumsan quis. Phasellus lacus ex, hendrerit convallis orci eu, hendrerit rhoncus lectus. Aenean imperdiet lacus et ex ultrices vehicula. Sed felis risus, vestibulum id odio non, interdum cursus mauris. Maecenas mattis magna quis nibh luctus, vitae egestas enim tristique. Maecenas et ex at enim luctus ullamcorper consequat id tellus. Nullam efficitur ornare leo, ac tristique ligula dignissim at. Vestibulum ullamcorper, lectus et rutrum lacinia, tellus elit porttitor libero, ac porta massa ligula ut velit. Nam quis bibendum turpis, a ultrices odio. Duis consectetur efficitur nunc. Cras augue nulla, feugiat at velit non, scelerisque commodo magna. Pellentesque eu diam pretium, blandit elit ut, rutrum turpis.

Aliquam varius sollicitudin finibus. Aliquam id mattis leo. Cras commodo ante vel orci pulvinar semper. Fusce in neque nec arcu facilisis tempus eu vitae erat. Aenean iaculis odio lectus, posuere lacinia neque vestibulum vitae. In hac habitasse platea dictumst. Donec congue sodales tincidunt. Phasellus odio nisi, vehicula id bibendum consequat, maximus sit amet elit. Vestibulum eget congue erat, non ultricies erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sapien risus, sollicitudin a orci eget, iaculis tempor purus. Praesent eget pretium eros. Donec pharetra ante ac enim tristique, quis euismod ante ultrices. Praesent a suscipit urna, sit amet gravida orci. Nam commodo ac sem ac bibendum.

Vivamus eget enim pretium, cursus felis vitae, iaculis orci. Donec tincidunt augue ut ex iaculis, sit amet volutpat urna volutpat. Integer nulla augue, blandit vel purus non, pellentesque ornare mauris. Nulla malesuada, sem ac dictum tincidunt, felis est tincidunt massa, a molestie elit ante ac ipsum. Nam id molestie tortor. Morbi condimentum nisl eget sapien lacinia mollis. Aliquam sed consectetur massa, quis pulvinar nisl. Morbi sit amet tortor augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.'''.split('\n\n')

broker = redis.Redis(
    password=os.environ.get('REDIS_PASSWORD', ''),
    host=os.environ['REDIS_HOST'],
    port=int(os.environ['REDIS_PORT'])
)

broker.publish('lipsum', random.choice(messages))

logger.info('Just pushed a message to the `lipsum` channel.')
