version: '3.7'

x-service: &common
  env_file: envvars
  networks:
    - trainingk8snet
  restart: unless-stopped

services:

  pass:
    <<: *common
    image: redis:alpine
    container_name: trainingk8s-pass

  pull:
    <<: *common
    build:
      context: ./pull
      dockerfile: Dockerfile
    image: trainingk8s-pull
    container_name: trainingk8s-pull
    depends_on:
      - pass
    ports:
      - 5000:5000
    command: python pull.py

  push:
    <<: *common
    build:
      context: ./push
      dockerfile: Dockerfile
    image: trainingk8s-push
    container_name: trainingk8s-push
    depends_on:
      - pass
      - pull
    command: python push.py
    restart: "no"

networks:
  trainingk8snet:
    name: trainingk8snet
