# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

passImage:
  repository: redis
  version: alpine

pass:
  containerPort: 6379
  servicePort: 6379

pullImage:
  repository: trainingk8s-pull
  version: latest
  pullPolicy: Never

pushImage:
  repository: trainingk8s-push
  version: latest
  pullPolicy: Never
