apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.namePrefix" . }}-pass
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "chart.namePrefix" . }}-pass
  ports:
    - port: {{ .Values.pass.containerPort }}
      targetPort: {{ .Values.pass.servicePort }}
