plot:
  data:
    source: "constants/pi.dat"
    first: 0
    until: 1000
  color:
    gradient_start: "violet"
    gradient_until: "red"
  format:
    max_height: 3000
  style:
    stroke-linecap: "round"
    stroke-width: 4
