apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.namePrefix" . }}-conf1
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  API_PORT: "5000"
  HOARD: "false"
  INTERVAL: "1"
  LOG_LEVEL: DEBUG
  REDIS_HOST: {{ include "chart.namePrefix" . }}-pass
  REDIS_PORT: "6379"
