---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trainingk8s-conf1
data:
  API_PORT: "5000"
  HOARD: "false"
  INTERVAL: "1"
  LOG_LEVEL: DEBUG
  REDIS_PASSWORD: 7aPU2Qwufl
  REDIS_HOST: trainingk8s-pass
  REDIS_PORT: "6379"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: trainingk8s-push-once
spec:
  template:
    spec:
      containers:
      - name: trainingk8s-push-once
        image: trainingk8s-push:latest
        imagePullPolicy: Never
        command:
        - "python"
        - "push.py"
        envFrom:
        - configMapRef:
            name: trainingk8s-conf1
      restartPolicy: Never
